### ISSUE TITLE
Add support to specify a custom `item` name

### ISSUE THREAD

**Issue by murielsilveira** [quandyfactory/dicttoxml#19]
Add support to specify a custom `item` name.
e.g.:

    <?xml version="1.0" encoding="UTF-8" ?>
    <root>
        <my_list>
            <my_custom_item_name>
                <foo>Abc</foo>
                <bar>123</bar>
            </my_custom_item_name>
            <my_custom_item_name>
                <foo>Def</foo>
                <bar>456</bar>
            </my_custom_item_name>
        </my_list>
    </root>

instead of:

    <?xml version="1.0" encoding="UTF-8" ?>
    <root>
        <my_list>
            <item>
                <foo>Abc</foo>
                <bar>123</bar>
            </item>
            <item>
                <foo>Def</foo>
                <bar>456</bar>
            </item>
        </my_list>
    </root>

**Comment by badsequel** [comment]
Any progress on this?

**Comment by quandyfactory** [comment]
I'm not sure when I'll have a chance to implement this functionality. If someone doesn't want to wait and sends a pull request, I'll happily consider it.

**Comment by quandyfactory** [comment]
Not sure if it meets your specific needs, but version 1.7 includes the optional ability to define a function for naming items, taking the list parent element name as an argument.

**Comment by theshahzaibc** [comment]
I was having same issue and fixed using `item_func` 
I have tried` list_item_names` but it's not a valid parameter for `dicttoxml()` function.
So, you can use the same.
**Something like this:**

```
list_item_names_config = lambda x: 'custom-item-name'

Xml = dicttoxml(dataobject, custom_root='custom-root', item_func=list_item_names_config,
                                     attr_type=False)
```
