### ISSUE TITLE
Allow : in key

### ISSUE THREAD

**Issue by mbingel** [quandyfactory/dicttoxml#25]
According to Microsoft this is valid XML:

```
<mx:CurrencyCode>EUR</mx:CurrencyCode>
```

But dicttoxml turns

```
obj = { 'mx:CurrencyCode': 'EUR' }
xml = dicttoxml(obj, attr_type=False, root=False)
print(xml)
```

into 

```
<key name="mx:CurrencyCode">EUR</key>
```

instead of 

```
<mx:CurrencyCode>EUR</mx:CurrencyCode>
```

It would be great to have an option to switch that behavior off.

**Comment by iDev0urer** [comment]
So I was going to create a pull request here to add the namespacing functionality, but I figured it would require a complete rewrite of this plugin. So rather than rewrite this plugin I wrote my own. If anyone wants to take a look at it I have it here https://github.com/iDev0urer/xmler
