### ISSUE TITLE
Invalid links in pypi distribution

### ISSUE THREAD

**Issue by isaac-councill** [quandyfactory/dicttoxml#30]
The links page https://pypi.python.org/simple/dicttoxml/ contains broken build_url links, e.g.:

https://github.com/quandyfactory/dicttoxml/blob/master/dist/dicttoxml-1.5.7.tar.gz?raw=true

This confuses some build tools such as pants (http://pantsbuild.github.io/), which parse the link content.

**Comment by pypingou** [comment]
Thanks for that!
