### ISSUE TITLE
Support Decimal

### ISSUE THREAD

**Issue by jmagnusson** [quandyfactory/dicttoxml#35]
```python
>>> import dicttoxml
>>> from decimal import Decimal
>>> mydict = dict(mydecimal=Decimal('1.2345'))
>>> dicttoxml.convert_dict(mydict, False, 'objects', True)
TypeError: Unsupported data type: 1.2345 (Decimal)
```

**Comment by jmagnusson** [comment]
(Well at least it gives this more precise error when you've merged #34)

**Comment by quandyfactory** [comment]
You're right; dicttoxml should be able to accommodate Decimal values. Let me look into how best to implement this and I will push a fix shortly.

**Comment by quandyfactory** [comment]
It looks like the most generic way to test if an object is a number is to import `numbers` and then:

    isinstance(mydecimal, numbers.Number)

Unless I find anything better, I'm going to implement this.

**Comment by quandyfactory** [comment]
I went with `isinstance(mydecimal, numbers.Number)` as it seems to be the most generic way to test if something is numbery. Thanks for bringing this issue to my attention!

**Comment by jmagnusson** [comment]
Thank you @quandyfactory for fixing this! (Unlike what the README says :wink:)
