### ISSUE TITLE
codec error

### ISSUE THREAD

**Issue by beef9999** [quandyfactory/dicttoxml#36]
>>> a

{'body': '\xe6\xb4\xbb\xe5\x8a\xa8\xe8\xae\xa2\xe5\x8d\x95', 'mch_id': '10075693', 'out_trade_no': 'iT201ac2FuqnlLpgq0rtM74mh8MCL81b', 'total_fee': 888, 'appid': 'wxb16fc7aa939867f6', 'notify_url': 'http://wagon.cn/place_order_success', 'spbill_create_ip': '0.0.0.0', 'nonce_str': 'gxA4XI1gMAALItAHQlzaUoNIE4xCYA8N', 'trade_type': 'JSAPI', 'sign': '2D2BF7CD5263D1113E1AB5601059AF82'}

>>> dicttoxml.dicttoxml(a)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dicttoxml.py", line 257, in dicttoxml
    addline('<%s>%s</%s>' % (custom_root, convert(obj, ids, attr_type, parent=custom_root), custom_root))
  File "/usr/local/lib/python2.7/dist-packages/dicttoxml.py", line 134, in convert
    return convert_dict(obj, ids, parent, attr_type)
  File "/usr/local/lib/python2.7/dist-packages/dicttoxml.py", line 145, in convert_dict
    LOG.info('Looping inside convert_dict(): key="%s", val="%s", type(val)="%s"' % (key, val, type(val).__name__))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by quandyfactory** [comment]
Thanks for raising this issue. I will try to fix it later today.

**Comment by beef9999** [comment]
A little curious about the failing reason? Could you let me know what caused this error?

发自我的 iPhone

**Comment by quandyfactory** [comment]
Issue is fixed in version 1.6.4. The problem was a UnicodeDecodeError in the logging function when the module encountered the non-ASCII string in the `body` key. I had to write a function, `unicode_me()`, to support both Python 2.x and Python 3. Thanks again for reporting this issue.
