### ISSUE TITLE
use of mutable object in python signatures

### ISSUE THREAD

**Issue by ooldham** [quandyfactory/dicttoxml#43]
Examining v1.6.6 - I see 3 methods with mutable object in signature.
This is never a good idea.

def convert_kv(key, val, attr_type, attr={}):
def convert_bool(key, val, attr_type, attr={}):
def convert_none(key, val, attr_type, attr={}):

These should be changed to:
def convert_kv(key, val, attr_type, attr=None):
def convert_bool(key, val, attr_type, attr=None):
def convert_none(key, val, attr_type, attr=None):

And the following - or something similar, inserted after each LOG statement found in each method.

<pre>
    attr = dict() if attr is None else attr
    if not isinstance(attr, dict):
        raise TypeError("Unexpected type: attr={a}, type={t} vs dict".format(a=attr, t=type(attr).__name__))
</pre>

**Comment by ooldham** [comment]
type(attr).name)) should be:  type(attr).__name__))

**Comment by quandyfactory** [comment]
This will be fixed in v1.7.15.

**Comment by quandyfactory** [comment]
I have resolved this in version 1.7.15.
