### ISSUE TITLE
return str in py3

### ISSUE THREAD

**Issue by eprykhodko** [quandyfactory/dicttoxml#55]
The `.encode('utf-8')` that is done at the very end causes the returt type to be `bytes` in py3. 
is there a reason the dicttoxml function does't return str in py3?

**Comment by tracy-ash** [comment]
yeah, I then need to .decode()

**Comment by quandyfactory** [comment]
This is a good point - I will look into addressing this in the next release.

**Comment by quandyfactory** [comment]
This is addressed in version 1.7.14.
