### ISSUE TITLE
dicttoxml generates INFO logs 

### ISSUE THREAD

**Issue by chintanvadgama** [quandyfactory/dicttoxml#60]
I am using dicttoxml to convert some dictionary data into xml & It works fine. However, it prints every action in the logs. We always have to see the logs file to debug any issue we encounter during our testing. These logs are not at all useful for any other developer if the dictionary gets successfully converted into XML. 

I would be grateful if you could disable any type of logging as a default action. However, developer should be able to enable/disable logging using set_debug method.

Thanks a lot for amazing python module :) 

[dicttoxml_logs.log](https://github.com/quandyfactory/dicttoxml/files/1400522/dicttoxml_logs.log)

**Comment by andreibancioiu** [comment]
See this issue and a possible quick fix:

https://github.com/quandyfactory/dicttoxml/issues/58

**Comment by quandyfactory** [comment]
Fixed in version 1.7.7.
