### ISSUE TITLE
Fails on integer key names.

### ISSUE THREAD

**Issue by adamabernathy** [quandyfactory/dicttoxml#61]
When using an integer as a key name, fails to convert to XML.

**Comment by SimiCode** [comment]
Please convert your keys to strings first because the xml won't have pure numbers too

**Comment by richieadler** [comment]
Converting automatically those keys to strings in some fashion would be useful.
json.dumps() makes a conversion before dumping. Can something similar be done here?

**Comment by quandyfactory** [comment]
If you use an integer as the key name, dicttoxml automatically prepends a letter n to the key name to ensure the XML is well-formed.

However, I just noticed that the code fails if you use a floating point number as the key name, so this will be fixed in the next release.

**Comment by quandyfactory** [comment]
This is fixed in v1.7.14.
