### ISSUE TITLE
repeating tags

### ISSUE THREAD

**Issue by vaishnavm217** [quandyfactory/dicttoxml#70]
I would like to create repeating tags xml
```
<root>
   <head></head>
   <data></data>
  <data></data>
</root>
```

is this possible?

**Comment by ssvfx41** [comment]
I'm wondering the same - how to get duplicate keys from a python dict into nested tag in xml

**Comment by ReS4** [comment]
Since there is no way to have duplicate keys in a `dict`, so you should rename `data` keys to `data1`, `data2`, `data3`, ...
After creating xml, replace `data{i}` to `data`. 
It seems silly but it works sometimes!

```
d = dict(head="", data1="", data2="", data3="")
t = dicttoxml(final_dict, attr_type=False).decode("utf8")
for i in range(n):
    t = t.replace(f"data{i}", "data") #Python3
    t = t.replace("data{}".format(i), "data") #Python2.7
```
