### ISSUE TITLE
Parse XMLs created with dicttoxml

### ISSUE THREAD

**Issue by kvonkoni** [quandyfactory/dicttoxml#71]
XMLs created with your package solve a lot of the issues I encountered parsing/unparsing XMLs created using the xmltodict package (e.g. inferring data type, parsing empty/single element lists, etc.)

I need the ability to run this in reverse; to parse the XMLs I create and turn them back into dicts.

Would you accept a PR for this?

**Comment by quandyfactory** [comment]
I realize this is extremely late but there is already an [xmltodict](https://pypi.org/project/xmltodict/) library that may meet your needs.
