### ISSUE TITLE
Importing ABC directly from collections was deprecated and will be removed in Python 3.10. Use collections.abc

### ISSUE THREAD

**Issue by tirkarthi** [quandyfactory/dicttoxml#78]
```
dicttoxml.py
99:    if isinstance(val, collections.Iterable):
191:    if isinstance(obj, collections.Iterable):
235:        elif isinstance(val, collections.Iterable):
298:        elif isinstance(item, collections.Iterable):
```

**Comment by andli** [comment]
This is even for 3.9 now so... easy fix. Repo seems inactive though. Will author accept a PR?

**Comment by tirkarthi** [comment]
PR : https://github.com/quandyfactory/dicttoxml/pull/73

**Comment by kurt-hectic** [comment]
any idea what to do about the deprecation warning? It seems this repo has not been updated in 4 years. Is there a fork that is maintained or plans for a new maintainer?

**Comment by Sn3akyP3t3** [comment]
I too have now begun seeing this and I'm unclear what to do about it yet.

Here is how I encounter it
# df is a Pandas dataframe
```
dataDict = df.to_dict(orient="records")

xmlData = dicttoxml(dataDict).decode()
```

**Comment by astrochun** [comment]
I believe this was resolved via #91

**Comment by axmue** [comment]
Version 1.7.5 installed via 

pip3 install -e git+https://github.com/quandyfactory/dicttoxml.git#egg=dicttoxml

did'nt work for me. I had to add

```import collections.abc```

to make it work. Did'nt look into this very deep, was just a quick fix. 
Python version is 3.10.6

**Comment by quandyfactory** [comment]
This issue is now fixed.
