### ISSUE TITLE
'True' is not a valid value for 'boolean'

### ISSUE THREAD

**Issue by robinsonmhj** [quandyfactory/dicttoxml#81]
When converting boolean type from dict to xml, it is converted to 'True' instead of 'true'
According to https://www.w3.org/TR/xmlschema-2/#boolean,  'True' is not a valid value for 'boolean'

**Comment by mangin** [comment]
https://github.com/quandyfactory/dicttoxml/pull/84

**Comment by quandyfactory** [comment]
This issue is fixed in version 1.7.8.
