### ISSUE TITLE
Option to omit the xml declaration but keep the root or custom_root

### ISSUE THREAD

**Issue by htr3n** [quandyfactory/dicttoxml#82]
The generated XML is hard-coded to include a declaration `<?xml version="1.0" encoding="UTF-8" ?>` (which is well-formed and totally legit). Nonetheless, some cases, for instance, I would need to embed the generated XML inside another XML, I would prefer not having that line of declaration.

https://github.com/quandyfactory/dicttoxml/blob/2016fe9817ad03b26aa5f1a475f5b79ad6757b96/dicttoxml.py#L390

If I use `root=False`, then the whole root element and the declaration will be omit. But I would love to keep the root or custom root to make the generated code well-formed.

Thanks.

**Comment by quandyfactory** [comment]
Hi htr3n, I realize this reply comes *waaaay* late, but I am trying to make up for years of negligence in maintaining this code and would like to understand more specifically what you are asking for here.

**Comment by quandyfactory** [comment]
It sounds like you want to suppress just the `<?xml...>` declaration but keep the `<root>...</root>` element? Is that correct?

**Comment by quandyfactory** [comment]
OK, I have implemented this in version 1.7.15.
