### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by mangin** [quandyfactory/dicttoxml#87]
Hello,

We are using dicttoxml in our projects, and I personally like it very much.

We have noticed however that there has been some time without activity on the Github repository, and as I have tried to make a PR, I was wondering at the same time if you would like to transfer the maintenance responsibility.
I tried to reach you by mail, but you don't respond.

**Comment by adiroiban** [comment]
I think that a new contributor can just fork and find update the project/package name.

And there is also https://github.com/delfick/python-dict2xml

**Comment by mangin** [comment]
@adiroiban 
The main problem is not a changing the owner of the reposiory.

The main proble is PyPi repo. This repo is a dependency of some libraries.

**Comment by mangin** [comment]
On this week,
I'll write to PyPi. I think we wait enough.

**Comment by lukasz-mitka** [comment]
@mangin any updates?

**Comment by Ousret** [comment]
To this point, we should not expect any news.
I have forked the project and refreshed it https://github.com/Ousret/dicttoxml/blob/master/CHANGELOG.md#version-200

Also, published to pypi as `dicttoxml2` https://pypi.org/project/dicttoxml2/ tag 2.0.0, should act as a stand-in replacement. I have tested it for a month.
I could address minor changes and PR reviews to the best of my abilities (time-wise).

**Comment by lukasz-mitka** [comment]
@quandyfactory I've seen you have been active lately. Can you consider this?

**Comment by WolfgangFahl** [comment]
my unit tests for python 3.10 break with this outdated version I'd appreciate if there would be progress.

**Comment by quandyfactory** [comment]
Hi all, I am the worst maintainer in the world but am trying to get caught up in taking care of this package.
