### ISSUE TITLE
how to prevent xml escaping

### ISSUE THREAD

**Issue by ondiekisteven** [quandyfactory/dicttoxml#89]
Hi, when converting from dictionary to xml, how can i prevent escaping characters. For example, i am reading a .env file which contains credentials, but `&` is getting replaced with `&amp;`

how can i prevent this

**Comment by quandyfactory** [comment]
Include the optional cdata=True argument when calling the dicttoxml function and it will wrap the values in character data instead of escaping characters. Eg;

    >>> from dicttoxml import dicttoxml
    >>> cred = { 'username': 'foobar', 'password': 'fxkd&woot' }
    >>> output = dicttoxml(cred, cdata=True)
    >>> print(output)
    '<?xml version="1.0" encoding="UTF-8" ?><root><username type="str"><![CDATA[foobar]]></username><password type="str"><![CDATA[fxkd&woot]]></password></root>'
