### ISSUE TITLE
python 3.9.7: `pip install dicttoxml` is installing only `installed-filed.txt`

### ISSUE THREAD

**Issue by kaushalmodi** [quandyfactory/dicttoxml#92]
`pip install dicttoxml` is installing only a text file.

## python and pip Versions

```
> python --version
Python 3.9.7

> pip --version
pip 22.2.2 
```

## Command to reproduce the issue

```
pip install dicttoxml --prefix foo  
```

## Installed directory tree

```
foo/
└── lib/
   └── python3.9/
      └── site-packages/
         └── dicttoxml-1.7.4-py3.9.egg-info/
            └── installed-files.txt
```

**Comment by kaushalmodi** [comment]
If I roll back to Python 3.7.3 (but with the same pip version 22.2.2), and run `pip install dicttoxml --prefix foo`, the installation looks correct:

```
foo/
└── lib/
   └── python3.7/
      └── site-packages/
         ├── __pycache__/
         │  └── dicttoxml.cpython-37.pyc
         ├── dicttoxml-1.7.4.dist-info/
         │  ├── INSTALLER
         │  ├── LICENCE.txt
         │  ├── METADATA
         │  ├── RECORD
         │  ├── REQUESTED
         │  ├── WHEEL
         │  └── top_level.txt
         └── dicttoxml.py
```

**Comment by quandyfactory** [comment]
I have upgraded to version 1.7.8. Can you please try to see if you are still having this issue? I was not able to reproduce it.

**Comment by quandyfactory** [comment]
I haven't heard any more on this and wasn't able to reproduce the error so I'm closing the issue.

**Comment by kaushalmodi** [comment]
@quandyfactory I am sorry for not replying to this when you fixed this. 

I confirm that I see the `dicttoxml.py` getting installed with dicttoxml v1.7.16, python 3.9.7 and pip 22.3.1. Now, upon running `pip install dicttoxml --prefix foo`, I get:

```
foo/lib/python3.9/site-packages/
├── __pycache__/
│  └── dicttoxml.cpython-39.pyc
├── dicttoxml-1.7.16.dist-info/
│  ├── INSTALLER
│  ├── LICENCE.txt
│  ├── METADATA
│  ├── RECORD
│  ├── REQUESTED
│  ├── WHEEL
│  └── top_level.txt
└── dicttoxml.py
```

**Comment by quandyfactory** [comment]
Excellent, thank you for confirming it is resolved - and thanks again for taking the time to report the issue in the first place.
