### ISSUE TITLE
python 3.8: Support dropped in 1.7.5 but not mentioned in release notes or docs

### ISSUE THREAD

**Issue by ds-clearago** [quandyfactory/dicttoxml#95]
![image](https://user-images.githubusercontent.com/26897541/204488993-9cf4374d-b2a8-410a-bc9f-d0d69ec7db3b.png)
The readme says "This module should work in Python 2.6+ and Python 3."
https://github.com/quandyfactory/dicttoxml#version-175 doesn't mention anything about dropped version support.

Please either change docs or make package support py3.8 again.

Thanks

**Comment by quandyfactory** [comment]
Thank you - this issue is fixed in v1.7.12. The readme and build files are updated to specify that Python 3.6+ is supported.
