### ISSUE TITLE
logging issue

### ISSUE THREAD

**Issue by adrien-berchet** [quandyfactory/dicttoxml#98]
Since 1.7.13 the library fails at converting some nested types like `tuple` just because of the internal logger.
For example, this fails:
```python
dicttoxml({"a": 1, "b": (1, 2)})
```
Just because this line fails:
```python
LOG.info('Inside unicode_me(). val = "%s"' % (val))
```

**Comment by quandyfactory** [comment]
Thank you - this issue is resolved with version 1.7.16.
